### ISSUE TITLE
Add plant

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#1]
## Value Statement

As a user,
I need to add my own plants to the list,
so that I can organize my own plants in the list.

## Description

![add-plant](https://user-images.githubusercontent.com/71655386/99904842-e1043800-2ccd-11eb-8079-8e095c1db988.png)

## Acceptance Criteria

- [x] By clicking the + button in the list a form page opens up.
- [x] Name, species of the plant can be entered in a form
- [x] By clicking a "add button", in the form, the entry gets submitted to the list and the list page opens up
- [x] By clicking a "cancel button", in the form, the list page opens up without a new entry

## Tasks

- [x] Create a feature branch
- [x] Add a + button to the list component
- [x] Create a AddPlant-Form component in Styleguidist
- [x] Write component tests
- [x] Add styling
- [x] Add component to app

## Complexity

medium
