### ISSUE TITLE
Delete Plant

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#14]
## Value Statement

As a user
I need delete button
so that I can remove a plant from my list.

## Description (Text, Scribble, Wireframe, Design)

![delete-button](https://user-images.githubusercontent.com/71655386/100602060-b20c4880-3303-11eb-8712-3fa62f1f799f.png)

## Acceptance Criteria

- [x] It deletes a plant from the app and the database

## Tasks

- [x] Create a freature branch
- [x] Create a button component in styleguidist
- [x] Write delete function in backend
- [x] Write delete function in frontend
- [x] Add button to edit form
- [x] Update tests

## Complexity

small
