### ISSUE TITLE
Plant list

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#2]
## Value Statement

As a user,
I need a list that shows up when I open the app,
so that I can see the plants.

## Description

![plant-list](https://user-images.githubusercontent.com/71655386/99904391-da27f600-2cca-11eb-8b87-65ce1851d7eb.png)

## Acceptance Criteria

- [x] A list of plants that shows up when the app opens
- [x] One list item is a card with a **random** plant picture, name and sepcies

## Tasks

- [x] Create a feature branch
- [x] Create List component in Styleguidist
- [x] Write component tests
- [x] Create List Item component in Styleguidist
- [x] Write component tests
- [x] Add styling
- [x] Add to app

## Complexity

small
