### ISSUE TITLE
Add image

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#28]
## Value Statement

As a user
I need a image upload in the add and edit form,
so that I can upload my own pictures of my plants.

## Description (Text, Scribble, Wireframe, Design)

![Add Plant](https://user-images.githubusercontent.com/71655386/101340357-e6da4b80-387f-11eb-97bf-70af2a78624b.png)

## Acceptance Criteria

- [x] When you add a new Plant, you can click on a +Img Icon, so you can choose from your own pictures
- [x] When you edit a plant, you can change the picture and add a new picture

## Tasks

- [x] create a feature branch
- [x] create a new entity for images
- [x] add a img path to plant entity
- [x] write the upload functions in be
- [x] write the upload functions in fe
- [x] write/update component tests
- [x] add styling
- [x] add to app

## Complexity

large
