### ISSUE TITLE
Set own water & fertilizer interval

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#29]
## Value Statement

As a user
I need the possibility to change the water & fertilizer intervals
so that I can set my own timer.

## Description (Text, Scribble, Wireframe, Design)

![Plant Detail](https://user-images.githubusercontent.com/71655386/101341094-e0000880-3880-11eb-9f4e-788f147bc334.png)

## Acceptance Criteria

- [x] The user can click on little icons under the indicator bars
- [x] little windows open where she/he can set the interval
- [x] by hitting save the new interval is set and saved on the server

## Tasks

- [x] create feature branch
- [x] add setting icons to detail page
- [x] create setting window with styled components
- [x] add water and fertilizer interval to plant entity
- [x] write update function
- [x] connect backend and frontend
- [x] write tests
- [x] add to app

## Complexity

medium
