### ISSUE TITLE
Set up backend

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#3]
## Value Statement

As a user,
I need a backend,
so that the data from my plants dont get lost.

## Description (Text, Scribble, Wireframe, Design)

![Setup-Server](https://user-images.githubusercontent.com/71655386/99974695-96ec8680-2da1-11eb-89f6-ef8939777004.png)

## Acceptance Criteria

- [x] Receiving the data that get send by the add plant form
- [x] Respond to a fetch request from the plant list.

## Tasks

- [x] Create a feature branch
- [x] Make a entity for the plants, with ID, Name, Species, IMGurl
- [x] Write the functions for Get and Post for the controller
- [x] Add validation to the entity
- [x] Add validation to the add plant form
- [x] Add fetch functions to the form and plantlist
- [x] Write tests

## Complexity

large
