### ISSUE TITLE
DetailPage

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#4]
## Value Statement

As a user,
I need detailpage for my plants,
so that I can see a bigger picture and more infos of my plant.

## Description (Text, Scribble, Wireframe, Design)

![detail-page](https://user-images.githubusercontent.com/71655386/99976916-54787900-2da4-11eb-8ce5-7a5e75084f82.png)

## Acceptance Criteria

- [x] When you click on a Item in the plantlist the detailpage of that plant opens
- [x] The detailpage contains the name, a bigger picture, the species and a extra info
- [x] On the top left is a back arrow to get back to the plant list
- [x] The add plant form gets a extra inputfield so you can add extra infos to your plant.

## Tasks

- [x] Create a feature branch
- [x] Create detailpage component in Styleguidist
- [x] Write component test
- [x] Add input to add plant form
- [x] Rewrite component test for the form
- [x] Add new prop to the plant entity in backend
- [x] Add styling
- [x] Add to app

## Complexity

large
