### ISSUE TITLE
Edit Page

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#5]
## Value Statement

As a user,
I need edit page,
so that I can edit my plant entries.

## Description (Text, Scribble, Wireframe, Design)

![edit-plant](https://user-images.githubusercontent.com/71655386/99978768-a91cf380-2da6-11eb-9862-d6f55a0e58df.png)

## Acceptance Criteria

- [x] When you click on the edit icon in the top right the edit page opens
- [x] The current data is already in die inputfields and can be changed
- [x] When you click the update button the entry gets updates
- [x] When you click cancel you go back to the plant detail page

## Tasks

- [x] Create a feature branch
- [x] Reuse the Add plant form
- [x] Add edit icon to detail page
- [x] Update component tests
- [x] Write fetch function with method put
- [x] Write function for the controller to handle the put request
- [x] Add to app

## Complexity

large
