### ISSUE TITLE
Water & Fertilizer Bars

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#7]
## Value Statement

As a user
I need bars that indicate water and fertilizer status
so that see when I have to check if my plants need something.

## Description (Text, Scribble, Wireframe, Design)

![water-fertilizer(1)](https://user-images.githubusercontent.com/71655386/100103376-18f1b380-2e65-11eb-98d9-013327d78515.png)

## Acceptance Criteria

- [x] The bars length shrinks with every day
- [x] On the last day it gets red so the user sees if he has to check his plant
- [x] On the Detailpage are the days left under the bars

## Tasks

- [x] Create feature branch
- [x] Add property to plant entity for water date and fertilizer date (gets added when plant is added)
- [x] Write a function for the controller to get the data out of the database
- [x] Add a styled component to the plant card and the detail page for the bars
- [x] Write a function that uses the date data and calcs the days left
- [x] Write tests
- [x] Add styling
- [x] Add to app

## Complexity

large
