### ISSUE TITLE
Water & Fertilizer Reset

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#8]
## Value Statement

As a user,
I need a way to reset the water and fertilizer bars
so that they get reset when I cared for my plant.

## Description (Text, Scribble, Wireframe, Design)

![reset](https://user-images.githubusercontent.com/71655386/100105331-843c8500-2e67-11eb-8a7f-e40894ea6c99.png)

## Acceptance Criteria

- [x] Two buttons on the detail page that reset the timer for water & fertilizer when you click it

## Tasks

- [x] Create feature branch
- [x] Create button component/s in styleguidist
- [x] Write function that resets the date in the database for that plant
- [x] Write tests
- [x] Add styling
- [x] Add to detailpage

## Complexity

medium
