### ISSUE TITLE
Login, Registration

### ISSUE THREAD

**Issue by FabianAlleblas** [FabianAlleblas/capstone-project#9]
## Value Statement

As a user,
I need registration and login
so that my data is personalized in the database.

## Description (Text, Scribble, Wireframe, Design)

![registration-login](https://user-images.githubusercontent.com/71655386/100108026-a08df100-2e6a-11eb-825a-9b6e565ed74a.png)

## Acceptance Criteria

- [x] When you open the app you get a login, so you can use the app
- [x] On the bottom is a sign up button that opens a registration form
- [x] On the registration form is also a cancel button, but is returns to the login
- [x] On the plant list is a logout icon in the top right, after you get logged out the login page opens

## Tasks

- [x] Create feature branch
- [x] Create login page in styleguidist
- [x] Create user registration in styleguidist
- [x] Validate both
- [x] Create new entity for user in backend, with id, name, email, password
- [x] Create new entity for token in backend, with token, date
- [x] Link user and plant entity - One to Many
- [x] Link user and token entity - One to Many
- [x] Write the functions to post and get the user data
- [x] Write the functions to create and get token
- [x] Write functions to store token in localstorage and put is in request heads
- [x] Write a function that validates token so user can use the app
- [x] Write a function that deletes old tokens in the database
- [x] Write tests
- [x] Add styling
- [x] Add to app

## Complexity

Extra extra large
